name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v7

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go.sum

      - name: Generate mocks
        run: |
          make mock

      # Simple linting first using standard go tools
      - name: Run go fmt
        run: |
          make fmt
      
      - name: Run go vet
        run: |
          make vet

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v7

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go.sum

      - name: Build
        run: |
          make docker-build

      - name: Test
        run: |
          make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
