name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup kubebuilder
        run: |
          make kubebuilder

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt