name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Generate mocks
        run: |
          # Install mockgen
          go install github.com/golang/mock/mockgen@v1.6.0
          
          echo "Generating AWS API mocks directly..."
          mkdir -p pkg/awsapi/mocks
          
          # Generate mocks directly to fix import issues
          mockgen -destination=pkg/awsapi/mocks/mock_eksiface.go -package=mock_awsapi github.com/aws/aws-sdk-go/service/eks/eksiface EKSAPI
          mockgen -destination=pkg/awsapi/mocks/mock_iamiface.go -package=mock_awsapi github.com/aws/aws-sdk-go/service/iam/iamiface IAMAPI
          mockgen -destination=pkg/awsapi/mocks/mock_stsiface.go -package=mock_awsapi github.com/aws/aws-sdk-go/service/sts/stsiface STSAPI

      - name: Generate test ConfigMap
        run: |
          ./hack/generate-test-configmap.sh

      - name: Run Unit Tests
        run: |
          GO_TEST_MODE=true \
          go test -v ./api/... ./pkg/k8s/... ./pkg/logging/... ./pkg/validation/... -coverprofile=cover.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
