name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      # Docker is pre-installed on GitHub's Ubuntu 22.04 runner
      - name: Verify Docker Installation
        run: |
          docker --version
          docker info

      - name: Build
        run: |
          make docker-build

      # Use standard KIND installation from GitHub Actions
      - name: Install KIND
        uses: helm/kind-action@v1.8.0
        with:
          install_only: true

      - name: Create Kubeconfig directory
        run: |
          mkdir -p hack/tools
          echo "KUBECONFIG=${{ github.workspace }}/hack/tools/kubeconfig" >> $GITHUB_ENV

      - name: Create KIND cluster
        run: |
          kind create cluster --name iam-manager-test --kubeconfig=${{ github.workspace }}/hack/tools/kubeconfig --wait 5m
          echo "Using KIND cluster 'iam-manager-test'"
          kubectl --kubeconfig=${{ github.workspace }}/hack/tools/kubeconfig config use-context kind-iam-manager-test
          kubectl --kubeconfig=${{ github.workspace }}/hack/tools/kubeconfig cluster-info
          kubectl --kubeconfig=${{ github.workspace }}/hack/tools/kubeconfig get nodes -o wide

      - name: Deploy CRDs
        run: |
          kubectl --kubeconfig=${{ github.workspace }}/hack/tools/kubeconfig apply -f config/crd/bases/

      - name: Run Tests
        run: |
          KUBECONFIG=${{ github.workspace }}/hack/tools/kubeconfig make test

      - name: Cleanup KIND resources
        if: always()
        run: |
          kind delete cluster --name iam-manager-test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
