name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_version: 20.10

      - name: Build
        run: |
          make docker-build

      - name: Install KIND and Setup Cluster
        run: |
          make kind-install
          make kind-setup

      - name: Deploy CRDs
        run: |
          make kind-deploy

      - name: Run Tests
        run: |
          make test

      - name: Cleanup KIND resources
        if: always()
        run: |
          make kind-clean

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
