name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: go.sum
          
      - name: Generate mocks
        run: |
          make mock

      # Simple linting first using standard go tools
      - name: Run go fmt
        run: |
          make fmt
      
      - name: Run go vet
        run: |
          make vet

      # Run golangci-lint but allow it to fail - document issues for future PR
      - name: Run golangci-lint (Non-blocking)
        id: lint
        continue-on-error: true
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m --issues-exit-code=0

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: go.sum

      - name: Build
        run: |
          make docker-build

      - name: Test
        run: |
          make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
